// <auto-generated />
namespace HREFProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Hr_17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Hr_17));
        
        string IMigrationMetadata.Id
        {
            get { return "202004220145134_Hr_1.7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
